using System;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;

namespace LyricsWPF.Backend.Collector.Providers.NetEase.Json
{
    //Generated by https://json2csharp.com/ i love you
    public class NetEaseSearchResponse
    {
        [JsonProperty("result")]
        public NetEaseResultResponse NetEaseResultDataResponse { get; set; }

        [JsonProperty("code")]
        public int Code { get; set; }
    }
}
